name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Echo "meow" to hello.txt
      - name: Echo to hello.txt
        run: pwd
        shell: bash
