name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Create a directory named test123 in the home directory of cvadmin
      - name: Create test123 directory
        run: /home/cvadmin/./test.sh
      - name: Whoami
        run: whoami
# adding something else